file_format: "1"
id: d15k
name: direct15keys
type: shield
url: https://github.com/volker-kempert/left-hand-chords-zmk-keyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display

